### ISSUE TITLE
ERA5-land artefacts

### ISSUE THREAD

**Issue by cmahony** [bcgov/bc_climate_anomaly#9]
there appear to be some artefacts (noise) in the ERA5-land data, especially in the last 3 years. this would be worth investigating. 
![BC_tmean_annual_2014_2023_spatial_anomaly_plt](https://github.com/bcgov/bc_climate_anomaly/assets/17104005/62f21d17-518c-453d-8517-cb94f4e01bfc)

**Comment by aseemsharma1** [comment]
Will work on this.
